declare module '*.jpeg';
declare module '*.jpg';
declare module '*.png';
declare module '*.svg';
declare module '*.webp';
declare module 'swiper/css/bundle'
declare module 'swiper/css';
declare module 'swiper/css/bundle';
declare module 'swiper/css/effect-fade';
declare module 'swiper/css/effect-coverflow';
declare module 'swiper/css/pagination';
declare module 'swiper/css/navigation';